example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json 

app_name = 'mywatchlist'

urlpatterns = [
    path('html/', show_watchlist, name='show_watchlist'),
   
    path('xml/', show_xml, name='show_xml'), 

    path('json/', show_json, name='show_json'),


]

todolist/urls.py
from django.urls import path
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import show_todolist
from todolist.views import add_task
from todolist.views import show_json

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
     path('json/', show_json, name='show_json'),
    path('register/', register, name='register'), 

    path('login/', login_user, name='login'),

    path('logout/', logout_user, name='logout'),
     path('create-task/', create_task, name='create_task'),

    path('add/', add_task, name='add_task'),

]

tugas2pbpsc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
    path('todolist/json/', include('todolist.urls')),
    path('todolist/add/', include('todolist.urls')),
]

# TODO: Implement Routings Here

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchedList(models.Model):
    watched = models.CharField(max_length=300)
    title = models.TextField()
    rating = models.TextField()
    release_date= models.TextField()
    review = models.TextField()
    

todolist/models.py
from django.db import models
from django.contrib.auth.models import User
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.TextField()
    description = models.TextField()

todolist/forms.py
from django import forms
from .models import Task
class Form(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description",]
        labels = {'title': "Judul Task", "description": "Deskripsi Task",}

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.

# Create your views here.
data_barang_katalog = CatalogItem.objects.all()
context = {
    'list_barang': data_barang_katalog,
    'nama' : 'Stelline Claudia',
    'id' : '2106700933'
}
def show_katalog(request):
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchedList
from django.http import HttpResponse
from django.core import serializers
# Create your views here.
data_watchlist = MyWatchedList.objects.all()

context = {
    'watchlist': data_watchlist,
    'nama' : 'Stelline Claudia',
    'id' : '2106700933'

}
def show_watchlist(request):
    return render(request, "watchlist.html", context)
def show_xml(request):
    return HttpResponse(serializers.serialize("xml", data_watchlist), content_type="application/xml")
def show_json(request):
    return HttpResponse(serializers.serialize("json", data_watchlist), content_type="application/json")
    

todolist/views.py
from django.shortcuts import render
from todolist.models import Task
from todolist.forms import Form
from django.shortcuts import redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_task = Task.objects.filter(user=request.user)
    context = {
        
    'list_data': data_task,
    'nama' : 'Stelline Claudia',
    'id' : '2106700933',
    'user' : request.user,
}
    return render(request, "todolist.html", context)
def show_json(request):
    data =Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")   


@login_required(login_url='/todolist/login/')
@csrf_exempt
def add_task(request):
    if request.method == "POST":
        title = request.POST.get("judul")
        description = request.POST.get("deskripsi")
        Task.objects.create(title = title, description = description,user = request.user,date =datetime.datetime.now())
        return HttpResponse()
    else:
        return redirect("todolist:show_todolist")



def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response
def create_task(request):
    if request.method == 'POST':
        form = Form(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            form2 = Task(title = title, description = description,user = request.user,date =datetime.datetime.now())
            form2.save()
            return HttpResponseRedirect(reverse("todolist:show_todolist"))

    else:
        form = Form() 

    return render(request, 'create-task.html', {'form': form})

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>

  <table>
    <tr>
    <th>Item Name</th>
    <th>Item Price</th>
    <th>Item Stock</th>
    <th>Rating</th>
    <th>Description</th>
    <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
{% for barang in list_barang %}
    <tr>
      <th>{{barang.item_name}}</th>
      <th>{{barang.item_price}}</th>
      <th>{{barang.item_stock}}</th>
      <th>{{barang.rating}}</th>
      <th>{{barang.description}}</th>
      <th>{{barang.item_url}}</th>
    </tr>
{% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/watchlist.html
{% extends 'base.html' %}

{% block content %}

<h1>Tugas 3 PBP/PBD</h1>

<h5>Name: </h5>
<p>{{nama}}</p>

<h5>Student ID: </h5>
<p>{{id}}</p>
<table>
    <tr>
    <th>Watched</th>
    <th>Title</th>
    <th>Rating</th>
    <th>Release date</th>
    <th>Review</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
{% for movie in watchlist %}
    <tr>
        <th>{{movie.watched}}</th>
        <th>{{movie.title}}</th>
        <th>{{movie.rating}}</th>
        <th>{{movie.release_date}}</th>
        <th>{{movie.review}}</th>
    </tr>
{% endfor %}
</table>


{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create-task.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Create Task</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div class="create-todolist d-flex align-items-center justify-content-center">
            <form class="create-todolist-form text-center" method="POST" action="">
                <h5 class="text-center">Fill in your todolist!</h5>
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="title" placeholder="Title" class="form-control">
                </div>
                <div class="form-group">
                    <input type="text" name="description" placeholder="Description" class="form-control">
                </div>
                <input class="btn create-task_btn button-custom rounded-pill" type="submit" value="Submit" > 
             
                
              
            </form>
          
            
        </div>
         
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        
    </body>
    </html>

<style>@import url('https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900');
    body{
        font-family: 'Poppins', sans-serif;
        font-size: 16px;
        background: rgb(116, 89, 89) ;
        color: #c08e74;
    }
    .create-todolist{
        height: 100vh;
        width: 100%;
    }
    .create-todolist-form{
        margin: auto;
        width: 500px;
        padding: 25px;
          
    }
    .form-control{
        font-size: 13px;
        min-height: 60px;
    }
   
    .form-control:focus{
         box-shadow: 0 0 0 0.2rem #c08e74 ;
    }
    .button-custom{
        width: 320px;
        padding: 10px;
        background-color: 	#c08e74; 
    }
    .button-custom:focus{
        background-color: #583e3e; 
        box-shadow: 0 0 0 0.2rem #c08e74;; 
    }
</style>

todolist/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Login</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div class="login d-flex align-items-center justify-content-center">
            <form class="login-form text-center" method="POST" action="">
                {% csrf_token %}
                <h1 class="text-uppercase">Login</h1>
                {% if messages %}
                    <div class="massage">
                        {% for message in messages %}
                        <label class="massage">{{ message }} </label>
                        {% endfor %}
                    </div>
                    {% endif %}     
                <div class="form-group">
                    <input type="text" name="username" placeholder="Username" class="form-control">
                </div>
                <div class="form-group">
                    <input type="password" name="password" placeholder="Password" class="form-control">
                </div>
                <div class="no-account-link">
                    <label>Belum mempunyai akun? </label>
                    <a href="{% url 'todolist:register' %}">Buat Akun</a>
                </div >
                    
                <input class="btn login_btn button-custom rounded-pill" type="submit" value="Login" >
              
                
                
            </form>
            
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        
    </body>
    </html>

<style>@import url('https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900');
    body{
        font-family: 'Poppins', sans-serif;
        font-size: 16px;
        background: rgb(116, 89, 89) ;
        color: 	#c08e74;
    }
    .login{
        height: 100vh;
        width: 100%;
    }
    .login-form{
        margin: auto;
        width: 370px;
        padding: 25px;
    }
    .form-control{
        font-size: 13px;
        min-height: 48px;
    }
    .login-form a{
         color: #f1cfa5; 
    }
    .login-form a:hover{
        color:#fcf7f1; 
    }
    
    .no-account-link{
        font-size: 13px;
        color:rgb(28, 25, 25); 
    }
    .massage{
        font-size: 13px;
        color:rgb(237, 50, 50);
    }
    .button-custom{
        width: 320px;
        padding: 10px;
        background-color: 	#c08e74; 
    }
    .button-custom:focus{
        background-color: #583e3e; 
        box-shadow: 0 0 0 0.2rem #c08e74;; 
    }
    .form-control:focus{
        box-shadow: 0 0 0 0.2rem #c08e74 ;
    }
</style>

todolist/templates/register.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Registrasi Akun</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
         
        <div class="register  d-flex align-items-center justify-content-center">
            <form class="register-form" method="POST">
                {% csrf_token %}
                <h1 class="text-uppercase text-center">Create Account</h1>
                <p class="text-center">Please fill in this form to create an account.</p>
                <label class="warning">{{form.errors}}</label>
                <div class="register-group">
                    <label><b>{{form.username.label_tag}}</b></label>
                    <input type="text" name="username" placeholder="Username" class="form-control">
                    <div class="help-text">
                        {{form.username.help_text }}
                    </div>
                </div>
                <div class="register-group">
                    <label class="margin"><b>{{form.password1.label_tag}}</b></label>
                    <input type="password" name="password1" placeholder="Password" class="form-control">
                    <div class="help-text ">
                        {{form.password1.help_text }}
                    </div>
                </div>
                   
                <div class="register-group">
                    <label ><b>{{form.password2.label_tag}}</b></label>
                    <input type="password" name="password2" placeholder="Password confirmation" class="form-control">
                    <div class="help-text ">
                        {{form.password2.help_text }}
                    </div>
                </div>
                    
                    <input class="btn register_btn button-custom rounded-pill" type="submit" name="submit" value="Daftar" >
             
                
              
            </form>
          
            
        </div>
         
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        
    </body>
    </html>
    
<style>@import url('https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900');
    body{
      font-family: 'Poppins', sans-serif;
      font-size: 16px;
      background: rgb(185, 165, 165);
      color:rgb(116, 89, 89);
    }
    .register{
      height: 100vh;
      width: 100%;
    }
    .register-form{
      margin: auto;
      width: 500px;
      padding: 25px;
      
    }
    .form-control{
      font-size: 13px;
      min-height: 48px;
    }
    
    .help-text{
        font-size:11px;
    }
    .margin{
        margin-top: 15px;
    }    
    .label{
        font-size: 18px;
    }
    .warning{
        font-size: 13px;
        color:rgb(237, 50, 50);
    }
    .massage-1{
        font-size: 13px;
        text-align: center;
    }
    
    .button-custom{
        width: 320px;
        padding: 10px;
        background-color: rgb(143, 118, 118); 
        margin: auto;
        margin-top: 2em;
        display: block;
    }
    .button-custom:focus{
        background-color: rgb(84, 73, 73); 
        box-shadow: 0 0 0 0.2rem rgb(143, 118, 118); 
    }
    .form-control:focus{
      box-shadow: 0 0 0 0.2rem rgb(84, 73, 73); 
    }
    </style>

todolist/templates/todolist.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Todolist</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div class="todolist d-flex align-items-center justify-content-center">
            <form class="todolist-form text-center" method="POST">
                {% csrf_token %}
                <h1 class="text-uppercase">Todolist</h1>
                <p >User: {{user}}</p>
                <div class="modal" tabindex="-1" id="Modal">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title">Add Task</h5>
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <td>Judul</td>
                            <td><input type="text" name="judul" placeholder="Judul" class="form-control" id="input_judul"></td>
                  
                            <td>Deskripsi </td>
                            <td><input type="text" name="deskripsi" placeholder="Deskripsi" style="min-height: 100px" class="form-control" id="input_deskripsi"></td>
                        </div>
                        <div class="modal-footer">
                          <button id="create_task" class="btn button-custom rounded-pill" data-dismiss="modal">Add Task</button>
                        </div>
                      </div>
                    </div>
                  </div>
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th style>Judul </th>
                                    <th style>Deskripsi </th>
                                    <th style>Tanggal </th>
                                </tr>
                            </thead>
                            <tbody>
                                <p></p>
                            </tbody>
                        </table>
                <button type="button"  class="btn button-custom rounded-pill" data-bs-toggle="modal" data-bs-target="#Modal" id="Test">
                        Add Task
                      </button>
                <a href="{% url 'todolist:logout' %}" class="button-custom rounded-pill" >Logout</a> 
            </form>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script>
            
        function createTask(){
            var taskAmount = $(".table > tbody").children().length;
            for(var i = taskAmount; i >= 2; i--){
                $(".table > tbody > tr:nth-child(" + i + ")").remove();
            }

       
            $.get("json/", function(data) {
                for(var i = 0; i < data.length; i++){
                    var tr = document.createElement("tr");
                    var judul_td = document.createElement("td");
                    judul_td.append(data[i].fields.title);
                    var deskripsi_td = document.createElement("td");
                    deskripsi_td.append(data[i].fields.description);
                    var date_td = document.createElement("td");
                    date_td.append(data[i].fields.date);

                    tr.append(judul_td);
                    tr.append(deskripsi_td);
                    tr.append(date_td);

                    $(".table").append(tr);
                }
                });
        }

        $(document).ready(function(){
            createTask();
            function validate(){
                if ($('#input_judul').val().length > 0 &&
                    $('#input_deskripsi').val().length > 0) {
                    $("#Send-footer").prop("disabled", false);
                }
                else {
                    $("#Send-footer]").prop("disabled", true);
                }
            }
        $("#create_task").click(function(e){
            console.log("create todolist success");
            var judul = $("#input_judul").val();
            var deskripsi = $("#input_deskripsi").val();
            validate();
            $.post("add/",
            {
                judul,
                deskripsi,
            },
            function(data, status){
                console.log("create todolist success");
                createTask();
                $("#input_judul").val("");
                $("#input_deskripsi").val("");
                });
            
            });
        });
        $('#Test').click(function(e){
            e.preventDefault();
            $('#Modal').modal();
        });
        
        </script>
         
      
        
    </body>
    </html>

<style>@import url('https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900');
   
    .table{
    border-collapse: collapse;
    overflow: hidden;
    box-shadow: 0 0 20px rgba(0,0,0,0.1);
    background-color: rgba(255,255,255,0.2);
    color: rgb(116, 89, 89);
    }

    tbody tr:hover  {
    background:rgb(84, 73, 73);
    color:#FFFFFF;
    }

    body{
        font-family: 'Poppins', sans-serif;
        font-size: 16px;
        background: rgb(185, 165, 165);
        color:rgb(116, 89, 89);
    }
    thead {
        background-color:rgb(116, 89, 89);
        color:rgb(185, 161, 161);
        
    }
    .todolist{
        height: 100vh;
        width: 100%;
    }
    .todolist-form{
        margin: auto;
        
    }
    .button-custom{
        width: 320px;
        padding: 10px;
        background-color: rgb(143, 118, 118); 
        margin: auto;
        margin-top: 2em;
        display: block;
        color: rgb(0, 0, 0); 
        text-align: center;
    }
    .button-custom:focus{
        background-color: rgb(84, 73, 73); 
        box-shadow: 0 0 0 0.2rem rgb(143, 118, 118); 
    }
    .button-custom:hover{
        color:#dedae3;
    }
    
</style>